language: python
python:
  - "3.6"

install:
  - "pip install --upgrade pip"
  - "pip install -r ./requirements.txt"

script:
  - "python ./ima-quadro-resumo.py"
  - "python ./idka.py"

notifications:
  email:
    recipients:
      - royopa@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
